In [7]:
import numpy as np
import time
from algorithms import brute_force, nearest_neighbor
from utils import dist_matrix_generator

In [24]:
dist_matrix = dist_matrix_generator.generate(num_cities=11, min_dist=10, max_dist=100, seed = 22)

print(dist_matrix)

[[ 0 52 51 75 40 58 47 67 89 31 45]
 [52  0 39 13 28 82 31 67 94 84 50]
 [51 39  0 37 65 35 33 15 33 77 82]
 [75 13 37  0 60 55 49 65 77 74 33]
 [40 28 65 60  0 56 46 49 71 47 40]
 [58 82 35 55 56  0 52 93 96 57 56]
 [47 31 33 49 46 52  0 21 73 55 83]
 [67 67 15 65 49 93 21  0 49 46 84]
 [89 94 33 77 71 96 73 49  0 87 50]
 [31 84 77 74 47 57 55 46 87  0 58]
 [45 50 82 33 40 56 83 84 50 58  0]]


In [25]:
if len(dist_matrix) <= 12:
    start_time = time.time()
    path, distance = brute_force.solve(dist_matrix)
    end_time = time.time()
    execution_time = end_time - start_time

    print(f"BRUTE FORCE:")
    print(f"Putanja: {path}")
    print(f"Distanca: {distance:.2f}")
    print(f"Vreme izvršavanja: {execution_time:.6f} sekundi")
else:
    print(f"Broj gradova prevelik za brute force.")

start_time = time.time()
path, distance = nearest_neighbor.solve(dist_matrix)
end_time = time.time()
execution_time = end_time - start_time

print("----------------------")

print(f"NEAREST NEIGHBOR:")
print(f"Putanja: {path}")
print(f"Distanca: {distance:.2f}")
print(f"Vreme izvršavanja: {execution_time:.6f} sekundi\n")

BRUTE FORCE:
Putanja: [0, 4, 1, 3, 10, 8, 2, 7, 6, 5, 9, 0]
Distanca: 373.00
Vreme izvršavanja: 30.276166 sekundi
----------------------
NEAREST NEIGHBOR:
Putanja: [0, 9, 7, 2, 6, 1, 3, 10, 4, 5, 8, 0]
Distanca: 483.00
Vreme izvršavanja: 0.000000 sekundi

