In [1]:
import numpy as np
import time
from algorithms import brute_force, genetic_algorithm, nearest_neighbor
from utils import dist_matrix_generator

In [2]:
dist_matrix = dist_matrix_generator.generate(num_cities=10, min_dist=10, max_dist=100, seed = 22)

print(dist_matrix)

[[ 0 49 82 58 38 24 43 63 85 46]
 [49  0 33 56 42 38 92 29 49 89]
 [82 33  0 57 75 54 66 56 62 35]
 [58 56 57  0 21 67 97 54 48 82]
 [38 42 75 21  0 17 91 53 80 39]
 [24 38 54 67 17  0 48 52 57 62]
 [43 92 66 97 91 48  0 45 47 30]
 [63 29 56 54 53 52 45  0 95 52]
 [85 49 62 48 80 57 47 95  0 87]
 [46 89 35 82 39 62 30 52 87  0]]


In [3]:
algorithms = {
    "BRUTE FORCE" : brute_force,
    "NEAREST NEIGHBOR" : nearest_neighbor,
    "GENETIC ALGORITHM" : genetic_algorithm
}

for name, algo in algorithms.items():
    start_time = time.time()
    path, distance = algo.solve(dist_matrix)
    end_time = time.time()
    execution_time = end_time - start_time

    print(f"{name}:")
    if path == []:
        print("/")
    else:
        print(f"Putanja: {path}")
        print(f"Distanca: {distance:.2f}")
        print(f"Vreme izvršavanja: {execution_time:.6f} sekundi")
    print("-----------------------------------")

Broj gradova prevelik za brute force
BRUTE FORCE:
/
-----------------------------------
NEAREST NEIGHBOR:
Putanja: [0, 5, 4, 3, 8, 6, 9, 2, 1, 7, 0]
Distanca: 347.00
Vreme izvršavanja: 0.000000 sekundi
-----------------------------------
GENETIC ALGORITHM:
Putanja: [3, 8, 2, 1, 7, 6, 9, 0, 5, 4, 3]
Distanca: 355.00
Vreme izvršavanja: 0.421039 sekundi
-----------------------------------
